# Generated by Django 4.1.9 on 2023-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='address',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='dob',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='mobile',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
