# Generated by Django 4.1.9 on 2023-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archive/')),
                ('name', models.CharField(default='none', max_length=30)),
                ('dob', models.CharField(default='none', max_length=30)),
                ('mobile', models.CharField(default='none', max_length=30)),
                ('address', models.CharField(default='none', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='main/'),
        ),
    ]
