# Generated by Django 4.1.9 on 2023-08-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_archive_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
